#! /bin/bash
# biserver-ee   Bring up/down Pentaho Business Intelligence server
# chkconfig: - 85 10
# description: Pentaho Business Intelligence server start at boot time.
#
#
### BEGIN INIT INFO
# Provides: biserver-ee
# Required-Start $network $syslog $mysqld
# Required-Stop $network $syslog
# Default-Start:
# Default-Stop:
# Description: Pentaho Business Intelligence server start at boot time.
# Short-Description: start and stop biserver
### END INIT INFO 

# Source function library.
[ -f /etc/sysconfig/network ] || exit 0
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network

# Check that networking is up.
[ "${NETWORKING}" = "no" ] && exit 0

SU=/bin/su

#set environment variables
NAME=biserver-ee
FULLNAME="Pentaho Business Intelligence"
PENTAHOBI_HOME=/opt/pentaho/biserver-ee
PENTAHOBI_USR=pentaho
PENTAHOBI_GRP=pentaho
export PENTAHO_JAVA_HOME=/usr/lib/jvm/java-1.6.0-sun.x86_64


getpid() {
    # ps from rhel leaves a space as the first column so we must use the second field in cut
    PID=$(ps ax | grep $NAME | grep java | grep -v grep | cut -d" " -f2)
    echo $PID
}

start() {
    PID=$(getpid)
    if [ $PID"x" == "x" ]; then
        action $"Starting Pentaho Business Intelligence server" $SU -m $PENTAHOBI_USR -c $PENTAHOBI_HOME/start-pentaho.sh 
    else
        action $"Starting Pentaho Business Intelligence server" /bin/false
    fi
}

stop() {
    PID=$(getpid)
    if [ $PID"x" != "x" ]; then
        action $"Stopping Pentaho Business Intelligence server" $SU -m $PENTAHOBI_USR -c $PENTAHOBI_HOME/stop-pentaho.sh 
    else
        action $"Stopping Pentaho Business Intelligence server" /bin/false
    fi
}

restart() {
    stop
    PID=$(getpid)
    while [ $PID"x" != "x" ]; do
        sleep 1
        echo -n .
    done
    start
}

status() {
    PID=$(getpid)
    if [ $PID"x" == "x" ]; then
        echo "$FULLNAME($NAME) is stopped"
    else
        echo "$FULLNAME($NAME) is started with pid $PID"
    fi
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 1
esac

exit 0
