#! /bin/bash
# pdi-ee   Bring up/down Pentaho Data Integration server
# chkconfig: 345 85 10
# description: Pentaho Data Integration server start at boot time.
#
#
### BEGIN INIT INFO
# Provides: pdi-ee
# Required-Start $network $syslog $mysqld
# Required-Stop $network $syslog
# Default-Start:
# Default-Stop:
# Description: Pentaho Data Integration server start at boot time.
# Short-Description: start and stop pdi-ee
### END INIT INFO 

# Source function library.
[ -f /etc/sysconfig/network ] || exit 0
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network

# Check that networking is up.
[ "${NETWORKING}" = "no" ] && exit 0

SU=/bin/su

#set environment variables
NAME=pdi-ee
FULLNAME="Pentaho Data Integration"
PENTAHOPDI_HOME=/opt/pentaho/pdi-ee/data-integration-server
PENTAHOPDI_USR=pentaho
PENTAHOPDI_GRP=pentaho
export PENTAHO_JAVA_HOME=/usr/lib/jvm/java-1.6.0-sun.x86_64


getpid() {
    PID=$(ps ax | grep $NAME | grep java | grep -v grep | awk '{print $1}' )
    echo $PID
}

start() {
    if [ $(getpid)"x" == "x" ]; then
        pushd $PENTAHOPDI_HOME > /dev/null
        action $"Starting Pentaho Data Integration server" $SU -m $PENTAHOPDI_USR -c "$PENTAHOPDI_HOME/start-pentaho.sh >> $PENTAHOPDI_HOME/tomcat/logs/startup.log"
        popd $PENTAHOPDI_HOME > /dev/null
    else
        action $"Starting Pentaho Data Integration server" /bin/false
    fi
}

stop() {
    if [ $(getpid)"x" != "x" ]; then
        pushd $PENTAHOPDI_HOME > /dev/null
        CURRPID=$(getpid)
        action $"Stopping Pentaho Data Integration server" $SU -m $PENTAHOPDI_USR -c "kill -9 $CURRPID"
        popd $PENTAHOPDI_HOME > /dev/null
    else
        action $"Stopping Pentaho Data Integration server" /bin/false
    fi
}

restart() {
    stop
    echo "Waiting for the process to stop"
    while [ $(getpid)"x" != "x" ]; do
        sleep 1
        echo -n .
    done
    echo
    start
}

status() {
    PID=$(getpid)
    if [ $PID"x" == "x" ]; then
        echo "$FULLNAME($NAME) is stopped"
    else
        echo "$FULLNAME($NAME) is started with pid $PID"
    fi
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 1
esac

exit 0
