#! /bin/bash
# pentahobi   Bring up/down Pentaho Business Intelligence server
# chkconfig: - 85 10
# description: Pentaho Business Intelligence server start at boot time.
#
#
### BEGIN INIT INFO
# Provides: pentaho-bi
# Required-Start $network $syslog $mysqld
# Required-Stop $network $syslog
# Default-Start:
# Default-Stop:
# Description: Pentaho Business Intelligence server start at boot time.
# Short-Description: start and stop pentaho bi
### END INIT INFO 

# Source function library.
[ -f /etc/sysconfig/network ] || exit 0
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network

# Check that networking is up.
[ "${NETWORKING}" = "no" ] && exit 0

SU=/bin/su

#set environment variables
NAME=pentahobi
PENTAHOBI_HOME=/opt/pentaho/biserver-ee
PENTAHOBI_USR=pentaho
PENTAHOBI_GRP=pentaho
export PENTAHO_JAVA_HOME=/usr/lib/jvm/java-1.6.0-sun.x86_64


start() {
    action $"Starting Pentaho Business Intelligence server" $SU -m $PENTAHOBI_USR -c $PENTAHOBI_HOME/start-pentaho.sh 
}

stop() {
    action $"Stopping Pentaho Business Intelligence server" $SU -m $PENTAHOBI_USR -c $PENTAHOBI_HOME/stop-pentaho.sh 
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 10s
        start
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
